// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_TIMEOBSERVER_STATIC_STRUCT3_H_
#define FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_TIMEOBSERVER_STATIC_STRUCT3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 4,
             "Non-compatible flatbuffers version included");

namespace sample {
namespace schema {
namespace TimeObserver {
namespace Static {
namespace struct1 {

struct Offset_Signal;
struct Offset_SignalBuilder;
struct Offset_SignalT;

}  // namespace struct1

namespace struct2 {

struct Delay_Signal;
struct Delay_SignalBuilder;
struct Delay_SignalT;

}  // namespace struct2

namespace struct3 {

struct OffsetQualityAware;
struct OffsetQualityAwareBuilder;
struct OffsetQualityAwareT;

}  // namespace struct3

namespace struct1 {

struct Offset_SignalT : public ::flatbuffers::NativeTable {
  typedef Offset_Signal TableType;
  int64_t offset_us = 0;
  uint64_t edgetimestamp_us = 0;
};

struct Offset_Signal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Offset_SignalT NativeTableType;
  typedef Offset_SignalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OFFSET_US = 4,
    VT_EDGETIMESTAMP_US = 6
  };
  int64_t offset_us() const {
    return GetField<int64_t>(VT_OFFSET_US, 0);
  }
  uint64_t edgetimestamp_us() const {
    return GetField<uint64_t>(VT_EDGETIMESTAMP_US, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_OFFSET_US, 8) &&
           VerifyField<uint64_t>(verifier, VT_EDGETIMESTAMP_US, 8) &&
           verifier.EndTable();
  }
  Offset_SignalT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Offset_SignalT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Offset_Signal> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Offset_SignalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Offset_SignalBuilder {
  typedef Offset_Signal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_offset_us(int64_t offset_us) {
    fbb_.AddElement<int64_t>(Offset_Signal::VT_OFFSET_US, offset_us, 0);
  }
  void add_edgetimestamp_us(uint64_t edgetimestamp_us) {
    fbb_.AddElement<uint64_t>(Offset_Signal::VT_EDGETIMESTAMP_US, edgetimestamp_us, 0);
  }
  explicit Offset_SignalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Offset_Signal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Offset_Signal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Offset_Signal> CreateOffset_Signal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t offset_us = 0,
    uint64_t edgetimestamp_us = 0) {
  Offset_SignalBuilder builder_(_fbb);
  builder_.add_edgetimestamp_us(edgetimestamp_us);
  builder_.add_offset_us(offset_us);
  return builder_.Finish();
}

::flatbuffers::Offset<Offset_Signal> CreateOffset_Signal(::flatbuffers::FlatBufferBuilder &_fbb, const Offset_SignalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace struct1

namespace struct2 {

struct Delay_SignalT : public ::flatbuffers::NativeTable {
  typedef Delay_Signal TableType;
  int64_t roundTripDelay_us = 0;
  uint64_t edgetimestamp_us = 0;
};

struct Delay_Signal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Delay_SignalT NativeTableType;
  typedef Delay_SignalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROUNDTRIPDELAY_US = 4,
    VT_EDGETIMESTAMP_US = 6
  };
  int64_t roundTripDelay_us() const {
    return GetField<int64_t>(VT_ROUNDTRIPDELAY_US, 0);
  }
  uint64_t edgetimestamp_us() const {
    return GetField<uint64_t>(VT_EDGETIMESTAMP_US, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ROUNDTRIPDELAY_US, 8) &&
           VerifyField<uint64_t>(verifier, VT_EDGETIMESTAMP_US, 8) &&
           verifier.EndTable();
  }
  Delay_SignalT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Delay_SignalT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Delay_Signal> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Delay_SignalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Delay_SignalBuilder {
  typedef Delay_Signal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_roundTripDelay_us(int64_t roundTripDelay_us) {
    fbb_.AddElement<int64_t>(Delay_Signal::VT_ROUNDTRIPDELAY_US, roundTripDelay_us, 0);
  }
  void add_edgetimestamp_us(uint64_t edgetimestamp_us) {
    fbb_.AddElement<uint64_t>(Delay_Signal::VT_EDGETIMESTAMP_US, edgetimestamp_us, 0);
  }
  explicit Delay_SignalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Delay_Signal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Delay_Signal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Delay_Signal> CreateDelay_Signal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t roundTripDelay_us = 0,
    uint64_t edgetimestamp_us = 0) {
  Delay_SignalBuilder builder_(_fbb);
  builder_.add_edgetimestamp_us(edgetimestamp_us);
  builder_.add_roundTripDelay_us(roundTripDelay_us);
  return builder_.Finish();
}

::flatbuffers::Offset<Delay_Signal> CreateDelay_Signal(::flatbuffers::FlatBufferBuilder &_fbb, const Delay_SignalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace struct2

namespace struct3 {

struct OffsetQualityAwareT : public ::flatbuffers::NativeTable {
  typedef OffsetQualityAware TableType;
  int64_t offset_us = 0;
  uint64_t edgetimestamp_us = 0;
  int64_t StatusCode = 0;
};

struct OffsetQualityAware FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OffsetQualityAwareT NativeTableType;
  typedef OffsetQualityAwareBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OFFSET_US = 4,
    VT_EDGETIMESTAMP_US = 6,
    VT_STATUSCODE = 8
  };
  int64_t offset_us() const {
    return GetField<int64_t>(VT_OFFSET_US, 0);
  }
  uint64_t edgetimestamp_us() const {
    return GetField<uint64_t>(VT_EDGETIMESTAMP_US, 0);
  }
  int64_t StatusCode() const {
    return GetField<int64_t>(VT_STATUSCODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_OFFSET_US, 8) &&
           VerifyField<uint64_t>(verifier, VT_EDGETIMESTAMP_US, 8) &&
           VerifyField<int64_t>(verifier, VT_STATUSCODE, 8) &&
           verifier.EndTable();
  }
  OffsetQualityAwareT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(OffsetQualityAwareT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<OffsetQualityAware> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OffsetQualityAwareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct OffsetQualityAwareBuilder {
  typedef OffsetQualityAware Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_offset_us(int64_t offset_us) {
    fbb_.AddElement<int64_t>(OffsetQualityAware::VT_OFFSET_US, offset_us, 0);
  }
  void add_edgetimestamp_us(uint64_t edgetimestamp_us) {
    fbb_.AddElement<uint64_t>(OffsetQualityAware::VT_EDGETIMESTAMP_US, edgetimestamp_us, 0);
  }
  void add_StatusCode(int64_t StatusCode) {
    fbb_.AddElement<int64_t>(OffsetQualityAware::VT_STATUSCODE, StatusCode, 0);
  }
  explicit OffsetQualityAwareBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OffsetQualityAware> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OffsetQualityAware>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OffsetQualityAware> CreateOffsetQualityAware(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t offset_us = 0,
    uint64_t edgetimestamp_us = 0,
    int64_t StatusCode = 0) {
  OffsetQualityAwareBuilder builder_(_fbb);
  builder_.add_StatusCode(StatusCode);
  builder_.add_edgetimestamp_us(edgetimestamp_us);
  builder_.add_offset_us(offset_us);
  return builder_.Finish();
}

::flatbuffers::Offset<OffsetQualityAware> CreateOffsetQualityAware(::flatbuffers::FlatBufferBuilder &_fbb, const OffsetQualityAwareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace struct3

namespace struct1 {

inline Offset_SignalT *Offset_Signal::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Offset_SignalT>(new Offset_SignalT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Offset_Signal::UnPackTo(Offset_SignalT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = offset_us(); _o->offset_us = _e; }
  { auto _e = edgetimestamp_us(); _o->edgetimestamp_us = _e; }
}

inline ::flatbuffers::Offset<Offset_Signal> Offset_Signal::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Offset_SignalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateOffset_Signal(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Offset_Signal> CreateOffset_Signal(::flatbuffers::FlatBufferBuilder &_fbb, const Offset_SignalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Offset_SignalT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _offset_us = _o->offset_us;
  auto _edgetimestamp_us = _o->edgetimestamp_us;
  return sample::schema::TimeObserver::Static::struct1::CreateOffset_Signal(
      _fbb,
      _offset_us,
      _edgetimestamp_us);
}

}  // namespace struct1

namespace struct2 {

inline Delay_SignalT *Delay_Signal::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Delay_SignalT>(new Delay_SignalT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Delay_Signal::UnPackTo(Delay_SignalT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = roundTripDelay_us(); _o->roundTripDelay_us = _e; }
  { auto _e = edgetimestamp_us(); _o->edgetimestamp_us = _e; }
}

inline ::flatbuffers::Offset<Delay_Signal> Delay_Signal::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Delay_SignalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDelay_Signal(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Delay_Signal> CreateDelay_Signal(::flatbuffers::FlatBufferBuilder &_fbb, const Delay_SignalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Delay_SignalT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _roundTripDelay_us = _o->roundTripDelay_us;
  auto _edgetimestamp_us = _o->edgetimestamp_us;
  return sample::schema::TimeObserver::Static::struct2::CreateDelay_Signal(
      _fbb,
      _roundTripDelay_us,
      _edgetimestamp_us);
}

}  // namespace struct2

namespace struct3 {

inline OffsetQualityAwareT *OffsetQualityAware::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<OffsetQualityAwareT>(new OffsetQualityAwareT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void OffsetQualityAware::UnPackTo(OffsetQualityAwareT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = offset_us(); _o->offset_us = _e; }
  { auto _e = edgetimestamp_us(); _o->edgetimestamp_us = _e; }
  { auto _e = StatusCode(); _o->StatusCode = _e; }
}

inline ::flatbuffers::Offset<OffsetQualityAware> OffsetQualityAware::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OffsetQualityAwareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateOffsetQualityAware(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<OffsetQualityAware> CreateOffsetQualityAware(::flatbuffers::FlatBufferBuilder &_fbb, const OffsetQualityAwareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const OffsetQualityAwareT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _offset_us = _o->offset_us;
  auto _edgetimestamp_us = _o->edgetimestamp_us;
  auto _StatusCode = _o->StatusCode;
  return sample::schema::TimeObserver::Static::struct3::CreateOffsetQualityAware(
      _fbb,
      _offset_us,
      _edgetimestamp_us,
      _StatusCode);
}

}  // namespace struct3

namespace struct1 {

inline const sample::schema::TimeObserver::Static::struct1::Offset_Signal *GetOffset_Signal(const void *buf) {
  return ::flatbuffers::GetRoot<sample::schema::TimeObserver::Static::struct1::Offset_Signal>(buf);
}

inline const sample::schema::TimeObserver::Static::struct1::Offset_Signal *GetSizePrefixedOffset_Signal(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sample::schema::TimeObserver::Static::struct1::Offset_Signal>(buf);
}

inline bool VerifyOffset_SignalBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sample::schema::TimeObserver::Static::struct1::Offset_Signal>(nullptr);
}

inline bool VerifySizePrefixedOffset_SignalBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sample::schema::TimeObserver::Static::struct1::Offset_Signal>(nullptr);
}

inline const char *Offset_SignalExtension() {
  return "bfbs";
}

inline void FinishOffset_SignalBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sample::schema::TimeObserver::Static::struct1::Offset_Signal> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOffset_SignalBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sample::schema::TimeObserver::Static::struct1::Offset_Signal> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<sample::schema::TimeObserver::Static::struct1::Offset_SignalT> UnPackOffset_Signal(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sample::schema::TimeObserver::Static::struct1::Offset_SignalT>(GetOffset_Signal(buf)->UnPack(res));
}

inline std::unique_ptr<sample::schema::TimeObserver::Static::struct1::Offset_SignalT> UnPackSizePrefixedOffset_Signal(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sample::schema::TimeObserver::Static::struct1::Offset_SignalT>(GetSizePrefixedOffset_Signal(buf)->UnPack(res));
}

}  // namespace struct1
}  // namespace Static
}  // namespace TimeObserver
}  // namespace schema
}  // namespace sample

#endif  // FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_TIMEOBSERVER_STATIC_STRUCT3_H_
