// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_H_
#define FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 4,
             "Non-compatible flatbuffers version included");

namespace sample {
namespace schema {

struct TimeObserver;
struct TimeObserverBuilder;
struct TimeObserverT;

struct TimeObserverT : public ::flatbuffers::NativeTable {
  typedef TimeObserver TableType;
  int64_t offset = 0;
  uint64_t edgetimestamp = 0;
  uint64_t observertimestamp = 0;
};

struct TimeObserver FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TimeObserverT NativeTableType;
  typedef TimeObserverBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OFFSET = 4,
    VT_EDGETIMESTAMP = 6,
    VT_OBSERVERTIMESTAMP = 8
  };
  int64_t offset() const {
    return GetField<int64_t>(VT_OFFSET, 0);
  }
  uint64_t edgetimestamp() const {
    return GetField<uint64_t>(VT_EDGETIMESTAMP, 0);
  }
  uint64_t observertimestamp() const {
    return GetField<uint64_t>(VT_OBSERVERTIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_OFFSET, 8) &&
           VerifyField<uint64_t>(verifier, VT_EDGETIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_OBSERVERTIMESTAMP, 8) &&
           verifier.EndTable();
  }
  TimeObserverT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TimeObserverT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TimeObserver> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TimeObserverT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TimeObserverBuilder {
  typedef TimeObserver Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_offset(int64_t offset) {
    fbb_.AddElement<int64_t>(TimeObserver::VT_OFFSET, offset, 0);
  }
  void add_edgetimestamp(uint64_t edgetimestamp) {
    fbb_.AddElement<uint64_t>(TimeObserver::VT_EDGETIMESTAMP, edgetimestamp, 0);
  }
  void add_observertimestamp(uint64_t observertimestamp) {
    fbb_.AddElement<uint64_t>(TimeObserver::VT_OBSERVERTIMESTAMP, observertimestamp, 0);
  }
  explicit TimeObserverBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TimeObserver> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TimeObserver>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TimeObserver> CreateTimeObserver(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t offset = 0,
    uint64_t edgetimestamp = 0,
    uint64_t observertimestamp = 0) {
  TimeObserverBuilder builder_(_fbb);
  builder_.add_observertimestamp(observertimestamp);
  builder_.add_edgetimestamp(edgetimestamp);
  builder_.add_offset(offset);
  return builder_.Finish();
}

::flatbuffers::Offset<TimeObserver> CreateTimeObserver(::flatbuffers::FlatBufferBuilder &_fbb, const TimeObserverT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TimeObserverT *TimeObserver::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TimeObserverT>(new TimeObserverT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TimeObserver::UnPackTo(TimeObserverT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = offset(); _o->offset = _e; }
  { auto _e = edgetimestamp(); _o->edgetimestamp = _e; }
  { auto _e = observertimestamp(); _o->observertimestamp = _e; }
}

inline ::flatbuffers::Offset<TimeObserver> TimeObserver::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TimeObserverT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTimeObserver(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TimeObserver> CreateTimeObserver(::flatbuffers::FlatBufferBuilder &_fbb, const TimeObserverT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TimeObserverT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _offset = _o->offset;
  auto _edgetimestamp = _o->edgetimestamp;
  auto _observertimestamp = _o->observertimestamp;
  return sample::schema::CreateTimeObserver(
      _fbb,
      _offset,
      _edgetimestamp,
      _observertimestamp);
}

inline const sample::schema::TimeObserver *GetTimeObserver(const void *buf) {
  return ::flatbuffers::GetRoot<sample::schema::TimeObserver>(buf);
}

inline const sample::schema::TimeObserver *GetSizePrefixedTimeObserver(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sample::schema::TimeObserver>(buf);
}

inline bool VerifyTimeObserverBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sample::schema::TimeObserver>(nullptr);
}

inline bool VerifySizePrefixedTimeObserverBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sample::schema::TimeObserver>(nullptr);
}

inline const char *TimeObserverExtension() {
  return "bfbs";
}

inline void FinishTimeObserverBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sample::schema::TimeObserver> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTimeObserverBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sample::schema::TimeObserver> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<sample::schema::TimeObserverT> UnPackTimeObserver(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sample::schema::TimeObserverT>(GetTimeObserver(buf)->UnPack(res));
}

inline std::unique_ptr<sample::schema::TimeObserverT> UnPackSizePrefixedTimeObserver(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sample::schema::TimeObserverT>(GetSizePrefixedTimeObserver(buf)->UnPack(res));
}

}  // namespace schema
}  // namespace sample

#endif  // FLATBUFFERS_GENERATED_SAMPLESCHEMA_SAMPLE_SCHEMA_H_
